; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = ./**/*platformio.ini

[env]
lib_deps = 
	waspinator/AccelStepper @ 1.61
	https://github.com/MobiFlight/LiquidCrystal_I2C#v1.1.4
	https://github.com/MobiFlight/Arduino-CmdMessenger#4.2.1
custom_lib_deps_atmel = 
	arduino-libraries/Servo @ 1.1.8
custom_lib_deps_pico = 
	ricaun/ArduinoUniqueID @ ^1.3.0
build_flags = 
	-DMF_REDUCE_FUNCT_LEDCONTROL
	-DMAXCALLBACKS=35
	-DSERIAL_RX_BUFFER_SIZE=256
	-DMESSENGERBUFFERSIZE=96
	-DMAXSTREAMBUFFERSIZE=96
	-DDEFAULT_TIMEOUT=5000
	-I./src/src
	-I./src/src/MF_Analog
	-I./src/src/MF_Button
	-I./src/src/MF_Encoder
	-I./src/src/MF_InputShifter
	-I./src/src/MF_DigInMux
	-I./src/src/MF_LCDDisplay
	-I./src/src/MF_Output
	-I./src/src/MF_OutputShifter
	-I./src/src/MF_Segment
	-I./src/src/MF_Servo
	-I./src/src/MF_Stepper
	-I./src/src/MF_Modules
build_src_filter = 
	+<*>
extra_scripts = 
	pre:get_version.py
	pre:get_CoreFiles.py
	copy_fw_files.py

[env_SF_OVHD]
build_flags = 
	-DMF_CUSTOMDEVICE_SUPPORT=1
	-DSSD1306_NO_SPLASH
	-DSH110X_NO_SPLASH
	-I./src/src/MF_CustomDevice
	-I./SF_OVHD
	-I./CustomDevices_own/Gagagu/Fonts
build_src_filter = 
	+<./MF_CustomDevice>
	+<../SF_OVHD>
lib_deps = 
	adafruit/Adafruit GFX Library @ ^1.11.9
	adafruit/Adafruit SSD1306 @ ^2.5.9
	adafruit/Adafruit SH110X @ ^2.1.10
custom_core_firmware_version = 2.5.1
custom_source_folder = SF_OVHD
custom_community_project = SF_OVHD
custom_community_folder = SF_OVHD

[env:SF_OVHD_mega]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = 
	${env.build_flags}
	${env_SF_OVHD.build_flags}
	-I./src/_Boards/Atmel/Board_Mega
	'-DMOBIFLIGHT_TYPE="SF OVHD Mega"'
	'-DMOBIFLIGHT_NAME="SF OVHD"'
build_src_filter = 
	${env.build_src_filter}
	${env_SF_OVHD.build_src_filter}
lib_deps = 
	${env.lib_deps}
	${env.custom_lib_deps_Atmel}
	${env_SF_OVHD.lib_deps}
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
	copy_fw_files.py
custom_core_firmware_version = ${env_SF_OVHD.custom_core_firmware_version}
custom_community_project = ${env_SF_OVHD.custom_community_project}
custom_source_folder = ${env_SF_OVHD.custom_source_folder}
custom_community_folder = ${env_SF_OVHD.custom_community_folder}

[env:SF_OVHD_raspberrypico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0M
lib_ldf_mode = chain+
upload_protocol = mbed
build_flags = 
	${env.build_flags}
	${env_SF_OVHD.build_flags}
	-I./src/_Boards/RaspberryPi/Pico
	'-DMOBIFLIGHT_TYPE="SF OVHD RaspiPico"'
	'-DMOBIFLIGHT_NAME="SF OVHD"'
build_src_filter = 
	${env.build_src_filter}
	${env_SF_OVHD.build_src_filter}
lib_deps = 
	${env.lib_deps}
	ricaun/ArduinoUniqueID @ ^1.3.0
	${env_SF_OVHD.lib_deps}
	gilesp1729/FontCollection@^0.9.0
monitor_speed = 115200
extra_scripts = 
	${env.extra_scripts}
	copy_fw_files.py
custom_core_firmware_version = ${env_SF_OVHD.custom_core_firmware_version}
custom_community_project = ${env_SF_OVHD.custom_community_project}
custom_source_folder = ${env_SF_OVHD.custom_source_folder}
custom_community_folder = ${env_SF_OVHD.custom_community_folder}
